service: alexa-experiment-notes

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-notes
    S3_BUCKET: meltzernotes-${opt:stage, self:provider.stage}
    AWS_ACCOUNT: ${file(config/alexa-config-${opt:stage, self:provider.stage}.yml):AWS_ACCOUNT}
    REGION: ${opt:region, self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/*"
    - Effect: "Allow"
      Action:
        - "s3:*" #"s3:PutBucketNotification"
      Resource: "*" # need to figure out how to give Rekognition access to the S3 bucket so I don't have to open up access to everyone.
         #Fn::Join:
         #  - ""
         #  - - "arn:aws:s3:::${self:provider.environment.S3_BUCKET}"
    - Effect: Allow
      Action:
        - rekognition:DetectText
      Resource: "*"
    - Effect: Allow
      Action:
        - polly:SynthesizeSpeech
      Resource: "*"

custom:
  alexa:
    vendorId: ${file(config/alexa-config-${opt:stage, self:provider.stage}.yml):AMAZON_VENDOR_ID}
    clientId: ${file(config/alexa-config-${opt:stage, self:provider.stage}.yml):AMAZON_CLIENT_ID}
    clientSecret: ${file(config/alexa-config-${opt:stage, self:provider.stage}.yml):AMAZON_CLIENT_SECRET}
    skills:
      - id: ${file(config/alexa-config-${opt:stage, self:provider.stage}.yml):ALEXA_SKILL_ID}
        manifest:
          publishingInformation:
            locales:
              en-US: 
                name: Meltzer Notes

          apis:
            custom:
              endpoint:  
                uri: arn:aws:lambda:${self:provider.region}:${self:provider.environment.AWS_ACCOUNT}:function:${self:service}-${self:provider.stage}-notesSkillIntentRouter
          manifestVersion: '1.0'
        models:
          en-US:
            interactionModel:
              languageModel:
                invocationName: meltzer's notes
                intents:
                  - name: GetNote
                    samples:
                     - "Get a note"
                     - "Give me a note" 
                     - "Get one"
                     - "Get it"
                  - name: AMAZON.StopIntent
                    samples:
                     - "goodbye"
                     - "bye"
                     - "exit"       
          
functions:
  notesSkillIntentRouter:
    handler: notesSkillIntentRouter.route
    events:
      - alexaSkill: ${file(config/alexa-config-${opt:stage, self:provider.stage}.yml):ALEXA_SKILL_ID}
  parseNoteImage:
    handler: parseNoteImage.parse
    events:
      - s3:
          bucket: ${self:provider.environment.S3_BUCKET}
          events:
            - s3:ObjectCreated:*
  createAudioForNote:
    handler: createAudioForNote.create
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - NotesDynamoDbTable
              - StreamArn
          batchSize: 1
          startingPosition: LATEST
          enabled: true 

resources:
  Resources:
    # The S3 bucket is already created by the framework when attaching a bucket to a lambda.
    #NotesS3Bucket:
    #  Type: 'AWS::S3::Bucket'
    #  Properties:
    #    BucketName: ${self:provider.environment.S3_BUCKET}
    #    AccessControl: Private
    NotesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: user
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userIndex
            KeySchema:
            - AttributeName: user
              KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: '1'
              WriteCapacityUnits: '1'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

plugins:
  - serverless-alexa-skills