service: alexa-experiment-notes

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-notes
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"


custom:
  alexa:
    vendorId: ${file(config/alexa-config.yml):AMAZON_VENDOR_ID}
    clientId: ${file(config/alexa-config.yml):AMAZON_CLIENT_ID}
    clientSecret: ${file(config/alexa-config.yml):AMAZON_CLIENT_SECRET}
    skills:
      - id: ${file(config/alexa-config.yml):ALEXA_SKILL_ID}
        manifest:
          publishingInformation:
            locales:
              en-US:
                name: Meltzer Notes

          apis:
            custom:
              endpoint:  
                uri: 'arn:aws:lambda:us-east-1:849835118694:function:alexa-experiment-notes-dev-testFunction' #need to figure out how to genericize this
                  #Fn::Join:
                  #  - ''
                  #  - - 'arn:aws:lambda:'
                  #    - Ref: AWS::Region
                  #    - ':'
                  #    - Ref: 'AWS::AccountId'
                  #    - ':function:${self:service}-${self:provider.stage}-testFunction'
          manifestVersion: '1.0'
        models:
          en-US:
            interactionModel:
              languageModel:
                invocationName: meltzer notes
                intents:
                  - name: MakeNote
                    samples:
                     - "Start a note"
                     - "Make a note" 
                     - "Create a note"
                     - "Make one"
                     - "Create one"        
          
functions:
  testFunction:
    handler: notesSkillIntentRouter.route
    events:
      - alexaSkill: ${file(config/alexa-config.yml):ALEXA_SKILL_ID}
      

resources:
  Resources:
    NotesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}


plugins:
  - serverless-alexa-skills
  - serverless-pseudo-parameters